title: "Processo Ágil - PDS Corporativo"
description: "Processo de desenvolvimento de software ágil para o PDS Corporativo"
theme: minima
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Site settings
url: ""
baseurl: ""
lang: pt-BR
